### PR TITLE
Sort imports

### PR DESCRIPTION
**Pull request by schneiderfelipe**
This sorts all imports in the code base with [isort](https://github.com/pycqa/isort/) (`isort .`).

### CODE REVIEW

**Review by BreezeWhite — COMMENTED** [review]
I don't see why there is a need to update the import convention.
Especially, I don't quite like the convention below:
``` python
from xxx import (a, b
                 c, d)

```

Still, thanks for your contribution.

**Comment by schneiderfelipe** [comment]
[This separates imports into groups and sorts each group lexicographically](https://google.github.io/styleguide/pyguide.html#313-imports-formatting). I think this is valuable. But I agree with you, this is ugly:

> ```python
> from xxx import (a, b
>                  c, d)
> ```

Would you be willing to accept this PR if I transform all such imports into the following?

```python
from xxx import a, b, c, d
```

**Comment by BreezeWhite** [comment]
I still prefer to leave as what it is now. I am used to current convention that sort imports order in line length, then imports having "as", and "import" goes before "from".

**Comment by schneiderfelipe** [comment]
> I still prefer to leave as what it is now. I am used to current convention that sort imports order in line length, then imports having "as", and "import" goes before "from".

Perfect, no problem! Closing.

**Pull request closed without merging**
